// twc/src/lib/projectData.ts

export interface Project {
  slug: string;
  title: string;
  image: string;
  category: string;
  description?: string;
  role?: string[];
  gallery?: string[];
  video?: string;
}

export const projectData: Project[] = [
  {
    slug: "sula-vineyards",
    title: "Sula Vineyards",
    image: "/lovable-uploads/SULA.png",
    category: "Alco-Bev",
    description: "Dummy page for Sula Vineyards project.",
    role: ["Brand Identity", "Activation"],
    gallery: ["/lovable-uploads/SULA.png"],
  },
  {
    slug: "york-winery",
    title: "YORK WINERY",
    image: "/lovable-uploads/YORK.png",
    category: "Alco-Bev",
    description: "Dummy page for YORK WINERY.",
    role: ["Design System", "Packaging"],
    gallery: ["/lovable-uploads/YORK.png"],
  },
  {
    slug: "rasa",
    title: "Rasa",
    image: "/lovable-uploads/RASA.png",
    category: "Alco-Bev",
    description: "Dummy page for Rasa.",
    role: ["Visual Strategy"],
    gallery: ["/lovable-uploads/RASA.png"],
  },
  {
    slug: "space",
    title: "SPACE",
    image: "/lovable-uploads/space.png",
    category: "F&B",
    description: "Dummy page for SPACE.",
    role: ["Brand Strategy"],
    gallery: ["/lovable-uploads/space.png"],
  },
  {
    slug: "elaan",
    title: "ELAAN",
    image: "/lovable-uploads/elaan.png",
    category: "Alco-Bev",
    description: "Dummy page for ELAAN.",
    role: ["Retail Collateral"],
    gallery: ["/lovable-uploads/elaan.png"],
  },
  {
    slug: "matero",
    title: "MATERO",
    image: "/lovable-uploads/matero.png",
    category: "F&B",
    description: "Dummy page for MATERO.",
    role: ["Visual Language"],
    gallery: ["/lovable-uploads/matero.png"],
  },
  {
    slug: "estate-monkeys",
    title: "Estate Monkeys",
    image: "/lovable-uploads/estatemonkey.png",
    category: "F&B",
    description: "Dummy page for Estate Monkeys.",
    role: ["Digital Branding"],
    gallery: ["/lovable-uploads/estatemonkey.png"],
  },
  {
    slug: "shakacan",
    title: "ShakaCan",
    image: "/lovable-uploads/shakacan.png",
    category: "Alco-Bev",
    description: "Dummy page for ShakaCan.",
    role: ["Packaging"],
    gallery: ["/lovable-uploads/shakacan.png"],
  },
  {
    slug: "the-source",
    title: "The Source",
    image: "/lovable-uploads/thesource.png",
    category: "Alco-Bev",
    description: "Dummy page for The Source.",
    role: ["Space Branding"],
    gallery: ["/lovable-uploads/thesource.png"],
  },
  {
    slug: "paul-and-mike",
    title: "Paul & Mike",
    image: "/lovable-uploads/paulandmike.png",
    category: "F&B",
    description: "Dummy page for Paul & Mike.",
    role: ["Brand Identity", "Packaging"],
    gallery: ["/lovable-uploads/paulandmike.png"],
  },
  {
    slug: "kiddopia",
    title: "KIDDOPIA",
    image: "/lovable-uploads/kiddopia.png",
    category: "Lifestyle",
    description: "Dummy page for KIDDOPIA.",
    role: ["Campaign Development"],
    gallery: ["/lovable-uploads/kiddopia.png"],
  },
  {
    slug: "naar",
    title: "NAAR",
    image: "/lovable-uploads/Naar.png",
    category: "Hospitality",
    description: "Dummy page for NAAR.",
    role: ["Visual Storytelling"],
    gallery: ["/lovable-uploads/Naar.png"],
  },
  {
    slug: "british-brewing-co",
    title: "British Brewing Co",
    image: "/lovable-uploads/Britishbrewingcompany.png",
    category: "Hospitality",
    description: "Dummy page for British Brewing Co.",
    role: ["Brand Expansion"],
    gallery: ["/lovable-uploads/Britishbrewingcompany.png"],
  },
  {
    slug: "momoland",
    title: "MOMOLAND",
    image: "/lovable-uploads/momoland.png",
    category: "Hospitality",
    description: "Dummy page for MOMOLAND.",
    role: ["Naming", "Brand Design"],
    gallery: ["/lovable-uploads/momoland.png"],
  },
  {
    slug: "buns-and-slices",
    title: "Buns & Slices",
    image: "/lovable-uploads/bunsandslices.png",
    category: "Hospitality",
    description: "Dummy page for Buns & Slices.",
    role: ["Social Media Design"],
    gallery: ["/lovable-uploads/bunsandslices.png"],
  },
  {
    slug: "copper-grillhouse",
    title: "COPPER Grillhouse",
    image: "/lovable-uploads/coppergrillhouse.png",
    category: "Hospitality",
    description: "Dummy page for COPPER Grillhouse.",
    role: ["Creative Strategy"],
    gallery: ["/lovable-uploads/coppergrillhouse.png"],
  },
  {
    slug: "beyond-by-sula",
    title: "BEYOND BY SULA",
    image: "/lovable-uploads/Beyond.png",
    category: "Hospitality",
    description: "Dummy page for BEYOND BY SULA.",
    role: ["Web Experience"],
    gallery: ["/lovable-uploads/Beyond.png"],
  },
  {
    slug: "sprig",
    title: "SPRIG",
    image: "/lovable-uploads/sprig.png",
    category: "F&B",
    description: "Dummy page for SPRIG.",
    role: ["Packaging", "Print"],
    gallery: ["/lovable-uploads/sprig.png"],
  },
  {
    slug: "provogue",
    title: "provogue",
    image: "/lovable-uploads/provogue.png",
    category: "Lifestyle",
    description: "Dummy page for provogue.",
    role: ["Retail Activation"],
    gallery: ["/lovable-uploads/provogue.png"],
  },
  {
    slug: "dsg",
    title: "DSG",
    image: "/lovable-uploads/DSG.png",
    category: "Event IP's",
    description: "Dummy page for DSG.",
    role: ["Event IP Branding"],
    gallery: ["/lovable-uploads/DSG.png"],
  }
];
